version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: ${MINIO_ADMIN_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ADMIN_PASSWORD}
    volumes:
      - minio_data:/minio_data
    command: server /data --console-address ":9090"

volumes:
  minio_data: